### ISSUE TITLE
Refactor `Signature` and `Proof` to be more consistent to `bls12_381-sign`

### ISSUE THREAD

**Issue by ZER0** [dusk-network/schnorr#81]
#### Summary
The way the two struct are defined are a bit weird:

1. The `Proof` should be called `DoubleSignature`
2. The `PublicKeyPair` shouldn't exists
3. We should have a method / function to `sign` and `verify` similar  how [bls12_381-sign](https://github.com/dusk-network/bls12_381-sign/)

#### Possible solution design or implementation
See the summary.

#### Additional context
See also #80

**Comment by HDauven** [comment]
Partially resolved by #89 #90.

**Comment by moCello** [comment]
point 2 will be resolved by #95

**Comment by moCello** [comment]
`verify` needs to be a method on the public key and not on the signatures
