### ISSUE TITLE
Improve `double_key::Proof` naming

### ISSUE THREAD

**Issue by moCello** [dusk-network/schnorr#89]
> Just noting that the name `Proof` is poorly chosen here since it could be mistaken for a
> plonk proof. In the `single_key` module this is named `Signature` which in my opinion is
> much more fitting. This is out of scope of this PR though and need to be tackled in a 
> new issue

_Originally posted by @moCello in https://github.com/dusk-network/schnorr/pull/88#discussion_r1374383113_

**Comment by HDauven** [comment]
I've got two concerns we have to keep in mind for an eventual implementation:
1. This will be a breaking change. There'll be a couple of places where we'll need to introduce this new `Signature` name.
2. If this is renamed to `Signature`, it'll have a name collision with the single key `Signature`. What we can do to fix this is to namespace both behind `dusk_schnorr::single_key::Signature` and `dusk_schnorr::double_key::Signature`.
